# -*- coding: utf-8 -*-
"""kunal ca1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gePr6B67OP8hHpCe36Iu3L7lUPQqaQ0x
"""

# led light brightness control using python.
import RPi.GPIO as GPIO
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider
import numpy as np

# Set up GPIO mode
GPIO.setmode(GPIO.BCM)

# Pin for LED
LED_PIN = 18

# Set up the LED pin as output
GPIO.setup(LED_PIN, GPIO.OUT)

# Create PWM instance with 1000 Hz frequency
pwm = GPIO.PWM(LED_PIN, 1000)
pwm.start(0)  # Start with 0% brightness

# Function to update PWM duty cycle based on slider value
def update(val):
    pwm.ChangeDutyCycle(slider.val)

# Create a figure and axis for Matplotlib
fig, ax = plt.subplots()
ax.set_title("LED Brightness Control")

# Set up the slider
ax_slider = plt.axes([0.1, 0.02, 0.8, 0.03], facecolor='lightgoldenrodyellow')
slider = Slider(ax_slider, 'Brightness', 0, 100, valinit=0, valstep=1)

# Connect the slider update function to the slider
slider.on_changed(update)

# Show the plot
plt.show()

# Clean up GPIO when done
pwm.stop()
GPIO.cleanup()

